-- Extended vocabulary data with 200+ words across multiple categories
-- This file extends the basic vocabulary with more comprehensive word lists

-- Clear existing vocabulary (optional - comment out if you want to keep existing data)
-- DELETE FROM public.vocabulary;

-- Basic Greetings and Politeness (20 words)
INSERT INTO public.vocabulary (thai_word, chinese_translation, pronunciation, category, difficulty_level, usage_example_thai, usage_example_chinese, tags) VALUES
('สวัสดี', '你好', 'sà-wàt-dii', 'greetings', 'beginner', 'สวัสดีครับ', '你好（男性用）', ARRAY['greeting', 'polite', 'daily']),
('สบายดีไหม', '你好吗', 'sà-baai dii mǎi', 'greetings', 'beginner', 'สบายดีไหมครับ', '你好吗？（男性用）', ARRAY['greeting', 'question', 'daily']),
('ขอบคุณ', '谢谢', 'khɔ̀ɔp khun', 'greetings', 'beginner', 'ขอบคุณมากครับ', '非常感谢（男性用）', ARRAY['gratitude', 'polite', 'daily']),
('ขอโทษ', '对不起', 'khɔ̌ɔ thôot', 'greetings', 'beginner', 'ขอโทษครับ', '对不起（男性用）', ARRAY['apology', 'polite', 'daily']),
('ลาก่อน', '再见', 'laa kɔ̀ɔn', 'greetings', 'beginner', 'ลาก่อนครับ', '再见（男性用）', ARRAY['farewell', 'polite', 'daily']),
('ยินดีที่ได้รู้จัก', '很高兴认识你', 'yin-dii thîi dâi rúu-jàk', 'greetings', 'intermediate', 'ยินดีที่ได้รู้จักครับ', '很高兴认识你（男性用）', ARRAY['greeting', 'introduction', 'polite']),
('ไม่เป็นไร', '没关系', 'mâi pen rai', 'greetings', 'beginner', 'ไม่เป็นไรครับ', '没关系（男性用）', ARRAY['response', 'polite', 'daily']),
('ขอโทษนะ', '不好意思', 'khɔ̌ɔ thôot ná', 'greetings', 'beginner', 'ขอโทษนะครับ', '不好意思（男性用）', ARRAY['apology', 'mild', 'daily']),
('ยินดีด้วย', '恭喜', 'yin-dii dûai', 'greetings', 'intermediate', 'ยินดีด้วยครับ', '恭喜（男性用）', ARRAY['congratulation', 'celebration', 'polite']),
('โชคดี', '祝你好运', 'chôok dii', 'greetings', 'beginner', 'โชคดีนะ', '祝你好运', ARRAY['blessing', 'encouragement', 'daily']),
('สวัสดีตอนเช้า', '早上好', 'sà-wàt-dii tɔɔn cháao', 'greetings', 'intermediate', 'สวัสดีตอนเช้าครับ', '早上好（男性用）', ARRAY['greeting', 'morning', 'time']),
('สวัสดีตอนเย็น', '晚上好', 'sà-wàt-dii tɔɔn yen', 'greetings', 'intermediate', 'สวัสดีตอนเย็นครับ', '晚上好（男性用）', ARRAY['greeting', 'evening', 'time']),
('ราตรีสวัสดิ์', '晚安', 'raa-trii sà-wàt', 'greetings', 'intermediate', 'ราตรีสวัสดิ์ครับ', '晚安（男性用）', ARRAY['farewell', 'night', 'polite']),
('เจอกันใหม่', '再见面', 'jəə gan mài', 'greetings', 'beginner', 'เจอกันใหม่นะ', '再见面', ARRAY['farewell', 'casual', 'daily']),
('ขอให้โชคดี', '祝好运', 'khɔ̌ɔ hâi chôok dii', 'greetings', 'intermediate', 'ขอให้โชคดีครับ', '祝好运（男性用）', ARRAY['blessing', 'formal', 'polite']),
('ยินดีต้อนรับ', '欢迎', 'yin-dii tɔ̂ɔn ráp', 'greetings', 'intermediate', 'ยินดีต้อนรับครับ', '欢迎（男性用）', ARRAY['welcome', 'hospitality', 'polite']),
('ขอบคุณมาก', '非常感谢', 'khɔ̀ɔp khun mâak', 'greetings', 'beginner', 'ขอบคุณมากครับ', '非常感谢（男性用）', ARRAY['gratitude', 'emphasis', 'polite']),
('ไม่มีปัญหา', '没问题', 'mâi mii pan-hǎa', 'greetings', 'intermediate', 'ไม่มีปัญหาครับ', '没问题（男性用）', ARRAY['response', 'assurance', 'daily']),
('ขอโทษจริงๆ', '真的对不起', 'khɔ̌ɔ thôot jing jing', 'greetings', 'intermediate', 'ขอโทษจริงๆ ครับ', '真的对不起（男性用）', ARRAY['apology', 'sincere', 'emphasis']),
('ขอบใจ', '谢谢（简短）', 'khɔ̀ɔp jai', 'greetings', 'beginner', 'ขอบใจครับ', '谢谢（男性用，简短）', ARRAY['gratitude', 'casual', 'daily']),

-- Numbers 1-20 and basic counting (25 words)
('หนึ่ง', '一', 'nɯ̀ng', 'numbers', 'beginner', 'หนึ่งคน', '一个人', ARRAY['number', 'counting', 'basic']),
('สอง', '二', 'sɔ̌ɔng', 'numbers', 'beginner', 'สองคน', '两个人', ARRAY['number', 'counting', 'basic']),
('สาม', '三', 'sǎam', 'numbers', 'beginner', 'สามคน', '三个人', ARRAY['number', 'counting', 'basic']),
('สี่', '四', 'sìi', 'numbers', 'beginner', 'สี่คน', '四个人', ARRAY['number', 'counting', 'basic']),
('ห้า', '五', 'hâa', 'numbers', 'beginner', 'ห้าคน', '五个人', ARRAY['number', 'counting', 'basic']),
('หก', '六', 'hòk', 'numbers', 'beginner', 'หกคน', '六个人', ARRAY['number', 'counting', 'basic']),
('เจ็ด', '七', 'jèt', 'numbers', 'beginner', 'เจ็ดคน', '七个人', ARRAY['number', 'counting', 'basic']),
('แปด', '八', 'pàet', 'numbers', 'beginner', 'แปดคน', '八个人', ARRAY['number', 'counting', 'basic']),
('เก้า', '九', 'gâo', 'numbers', 'beginner', 'เก้าคน', '九个人', ARRAY['number', 'counting', 'basic']),
('สิบ', '十', 'sìp', 'numbers', 'beginner', 'สิบคน', '十个人', ARRAY['number', 'counting', 'basic']),
('สิบเอ็ด', '十一', 'sìp èt', 'numbers', 'beginner', 'สิบเอ็ดคน', '十一个人', ARRAY['number', 'counting', 'teens']),
('สิบสอง', '十二', 'sìp sɔ̌ɔng', 'numbers', 'beginner', 'สิบสองคน', '十二个人', ARRAY['number', 'counting', 'teens']),
('สิบสาม', '十三', 'sìp sǎam', 'numbers', 'beginner', 'สิบสามคน', '十三个人', ARRAY['number', 'counting', 'teens']),
('สิบสี่', '十四', 'sìp sìi', 'numbers', 'beginner', 'สิบสี่คน', '十四个人', ARRAY['number', 'counting', 'teens']),
('สิบห้า', '十五', 'sìp hâa', 'numbers', 'beginner', 'สิบห้าคน', '十五个人', ARRAY['number', 'counting', 'teens']),
('สิบหก', '十六', 'sìp hòk', 'numbers', 'beginner', 'สิบหกคน', '十六个人', ARRAY['number', 'counting', 'teens']),
('สิบเจ็ด', '十七', 'sìp jèt', 'numbers', 'beginner', 'สิบเจ็ดคน', '十七个人', ARRAY['number', 'counting', 'teens']),
('สิบแปด', '十八', 'sìp pàet', 'numbers', 'beginner', 'สิบแปดคน', '十八个人', ARRAY['number', 'counting', 'teens']),
('สิบเก้า', '十九', 'sìp gâo', 'numbers', 'beginner', 'สิบเก้าคน', '十九个人', ARRAY['number', 'counting', 'teens']),
('ยี่สิบ', '二十', 'yîi sìp', 'numbers', 'beginner', 'ยี่สิบคน', '二十个人', ARRAY['number', 'counting', 'tens']),
('ร้อย', '一百', 'rɔ́ɔi', 'numbers', 'intermediate', 'หนึ่งร้อย', '一百', ARRAY['number', 'counting', 'hundreds']),
('พัน', '一千', 'phan', 'numbers', 'intermediate', 'หนึ่งพัน', '一千', ARRAY['number', 'counting', 'thousands']),
('หมื่น', '一万', 'mɯ̀ɯn', 'numbers', 'intermediate', 'หนึ่งหมื่น', '一万', ARRAY['number', 'counting', 'ten-thousands']),
('แสน', '十万', 'sǎen', 'numbers', 'advanced', 'หนึ่งแสน', '十万', ARRAY['number', 'counting', 'hundred-thousands']),
('ล้าน', '一百万', 'láan', 'numbers', 'advanced', 'หนึ่งล้าน', '一百万', ARRAY['number', 'counting', 'millions']),

-- Family and Relationships (20 words)
('แม่', '妈妈', 'mɛ̂ɛ', 'family', 'beginner', 'แม่ของฉัน', '我的妈妈', ARRAY['family', 'relationship', 'basic']),
('พ่อ', '爸爸', 'phɔ̂ɔ', 'family', 'beginner', 'พ่อของฉัน', '我的爸爸', ARRAY['family', 'relationship', 'basic']),
('ลูก', '孩子', 'lûuk', 'family', 'beginner', 'ลูกชาย', '儿子', ARRAY['family', 'relationship', 'basic']),
('พี่', '哥哥/姐姐', 'phîi', 'family', 'beginner', 'พี่ชาย', '哥哥', ARRAY['family', 'relationship', 'basic']),
('น้อง', '弟弟/妹妹', 'nɔ́ɔng', 'family', 'beginner', 'น้องสาว', '妹妹', ARRAY['family', 'relationship', 'basic']),
('ปู่', '爷爷（父方）', 'pùu', 'family', 'beginner', 'ปู่ของฉัน', '我的爷爷', ARRAY['family', 'grandparent', 'paternal']),
('ย่า', '奶奶（父方）', 'yâa', 'family', 'beginner', 'ย่าของฉัน', '我的奶奶', ARRAY['family', 'grandparent', 'paternal']),
('ตา', '爷爷（母方）', 'taa', 'family', 'beginner', 'ตาของฉัน', '我的外公', ARRAY['family', 'grandparent', 'maternal']),
('ยาย', '奶奶（母方）', 'yaai', 'family', 'beginner', 'ยายของฉัน', '我的外婆', ARRAY['family', 'grandparent', 'maternal']),
('ลุง', '叔叔/舅舅', 'lung', 'family', 'beginner', 'ลุงของฉัน', '我的叔叔', ARRAY['family', 'uncle', 'relative']),
('ป้า', '阿姨/姑姑', 'pâa', 'family', 'beginner', 'ป้าของฉัน', '我的阿姨', ARRAY['family', 'aunt', 'relative']),
('น้า', '叔叔（年轻）', 'náa', 'family', 'beginner', 'น้าของฉัน', '我的叔叔（年轻）', ARRAY['family', 'uncle', 'younger']),
('อา', '叔叔（年长）', 'aa', 'family', 'beginner', 'อาของฉัน', '我的叔叔（年长）', ARRAY['family', 'uncle', 'older']),
('สามี', '丈夫', 'sǎa-mii', 'family', 'intermediate', 'สามีของฉัน', '我的丈夫', ARRAY['family', 'spouse', 'marriage']),
('ภรรยา', '妻子', 'phan-ra-yaa', 'family', 'intermediate', 'ภรรยาของฉัน', '我的妻子', ARRAY['family', 'spouse', 'marriage']),
('แฟน', '男/女朋友', 'fɛɛn', 'family', 'beginner', 'แฟนของฉัน', '我的男/女朋友', ARRAY['family', 'relationship', 'dating']),
('ลูกชาย', '儿子', 'lûuk chaai', 'family', 'beginner', 'ลูกชายของฉัน', '我的儿子', ARRAY['family', 'child', 'male']),
('ลูกสาว', '女儿', 'lûuk sǎao', 'family', 'beginner', 'ลูกสาวของฉัน', '我的女儿', ARRAY['family', 'child', 'female']),
('หลาน', '孙子/孙女', 'lǎan', 'family', 'intermediate', 'หลานของฉัน', '我的孙子/孙女', ARRAY['family', 'grandchild', 'generation']),
('ครอบครัว', '家庭', 'khrɔ̂ɔp khrua', 'family', 'intermediate', 'ครอบครัวของฉัน', '我的家庭', ARRAY['family', 'collective', 'home']),

-- Food and Drinks (25 words)
('ข้าว', '米饭', 'khâao', 'food', 'beginner', 'กินข้าว', '吃饭', ARRAY['food', 'staple', 'daily']),
('น้ำ', '水', 'náam', 'food', 'beginner', 'ดื่มน้ำ', '喝水', ARRAY['drink', 'basic', 'daily']),
('อาหาร', '食物', 'aa-hǎan', 'food', 'beginner', 'อาหารไทย', '泰国菜', ARRAY['food', 'general', 'daily']),
('ผลไม้', '水果', 'phǒn-lá-máai', 'food', 'beginner', 'กินผลไม้', '吃水果', ARRAY['food', 'fruit', 'healthy']),
('เนื้อ', '肉', 'nɯ́a', 'food', 'beginner', 'เนื้อหมู', '猪肉', ARRAY['food', 'meat', 'protein']),
('ปลา', '鱼', 'plaa', 'food', 'beginner', 'กินปลา', '吃鱼', ARRAY['food', 'seafood', 'protein']),
('ไก่', '鸡肉', 'gài', 'food', 'beginner', 'เนื้อไก่', '鸡肉', ARRAY['food', 'poultry', 'protein']),
('หมู', '猪肉', 'mǔu', 'food', 'beginner', 'เนื้อหมู', '猪肉', ARRAY['food', 'pork', 'protein']),
('เนื้อวัว', '牛肉', 'nɯ́a wua', 'food', 'beginner', 'กินเนื้อวัว', '吃牛肉', ARRAY['food', 'beef', 'protein']),
('ผัก', '蔬菜', 'phàk', 'food', 'beginner', 'กินผัก', '吃蔬菜', ARRAY['food', 'vegetable', 'healthy']),
('นม', '牛奶', 'nom', 'food', 'beginner', 'ดื่มนม', '喝牛奶', ARRAY['drink', 'dairy', 'nutrition']),
('กาแฟ', '咖啡', 'gaa-fɛɛ', 'food', 'beginner', 'ดื่มกาแฟ', '喝咖啡', ARRAY['drink', 'beverage', 'caffeine']),
('ชา', '茶', 'chaa', 'food', 'beginner', 'ดื่มชา', '喝茶', ARRAY['drink', 'beverage', 'traditional']),
('เบียร์', '啤酒', 'bia', 'food', 'beginner', 'ดื่มเบียร์', '喝啤酒', ARRAY['drink', 'alcohol', 'social']),
('ไวน์', '葡萄酒', 'wai', 'food', 'intermediate', 'ดื่มไวน์', '喝葡萄酒', ARRAY['drink', 'alcohol', 'formal']),
('ขนมปัง', '面包', 'kha-nǒm pang', 'food', 'beginner', 'กินขนมปัง', '吃面包', ARRAY['food', 'bread', 'breakfast']),
('ไข่', '鸡蛋', 'khài', 'food', 'beginner', 'กินไข่', '吃鸡蛋', ARRAY['food', 'egg', 'protein']),
('เส้น', '面条', 'sên', 'food', 'beginner', 'กินเส้น', '吃面条', ARRAY['food', 'noodle', 'carb']),
('ซุป', '汤', 'súp', 'food', 'beginner', 'ดื่มซุป', '喝汤', ARRAY['food', 'soup', 'liquid']),
('สลัด', '沙拉', 'sa-làt', 'food', 'intermediate', 'กินสลัด', '吃沙拉', ARRAY['food', 'salad', 'healthy']),
('ขนม', '甜点', 'kha-nǒm', 'food', 'beginner', 'กินขนม', '吃甜点', ARRAY['food', 'dessert', 'sweet']),
('ไอศกรีม', '冰淇淋', 'ai-sa-griim', 'food', 'beginner', 'กินไอศกรีม', '吃冰淇淋', ARRAY['food', 'dessert', 'cold']),
('น้ำผลไม้', '果汁', 'náam phǒn-lá-máai', 'food', 'beginner', 'ดื่มน้ำผลไม้', '喝果汁', ARRAY['drink', 'juice', 'fruit']),
('น้ำแข็ง', '冰块', 'náam khǎeng', 'food', 'beginner', 'ใส่น้ำแข็ง', '加冰块', ARRAY['drink', 'ice', 'cold']),
('เครื่องดื่ม', '饮料', 'khrɯ̂ang dɯ̀ɯm', 'food', 'intermediate', 'สั่งเครื่องดื่ม', '点饮料', ARRAY['drink', 'beverage', 'general']);

-- Colors (15 words)
('สี', '颜色', 'sǐi', 'colors', 'beginner', 'สีแดง', '红色', ARRAY['color', 'basic', 'visual']),
('แดง', '红色', 'dɛɛng', 'colors', 'beginner', 'สีแดง', '红色', ARRAY['color', 'primary', 'basic']),
('เขียว', '绿色', 'khǐao', 'colors', 'beginner', 'สีเขียว', '绿色', ARRAY['color', 'primary', 'basic']),
('น้ำเงิน', '蓝色', 'náam ngəən', 'colors', 'beginner', 'สีน้ำเงิน', '蓝色', ARRAY['color', 'primary', 'basic']),
('เหลือง', '黄色', 'lɯ̌ang', 'colors', 'beginner', 'สีเหลือง', '黄色', ARRAY['color', 'primary', 'basic']),
('ส้ม', '橙色', 'sôm', 'colors', 'beginner', 'สีส้ม', '橙色', ARRAY['color', 'secondary', 'basic']),
('ม่วง', '紫色', 'mûang', 'colors', 'beginner', 'สีม่วง', '紫色', ARRAY['color', 'secondary', 'basic']),
('ชมพู', '粉色', 'chom-phuu', 'colors', 'beginner', 'สีชมพู', '粉色', ARRAY['color', 'light', 'basic']),
('ดำ', '黑色', 'dam', 'colors', 'beginner', 'สีดำ', '黑色', ARRAY['color', 'neutral', 'basic']),
('ขาว', '白色', 'khǎao', 'colors', 'beginner', 'สีขาว', '白色', ARRAY['color', 'neutral', 'basic']),
('เทา', '灰色', 'thao', 'colors', 'beginner', 'สีเทา', '灰色', ARRAY['color', 'neutral', 'basic']),
('น้ำตาล', '棕色', 'náam taan', 'colors', 'beginner', 'สีน้ำตาล', '棕色', ARRAY['color', 'earth', 'basic']),
('ทอง', '金色', 'thɔɔng', 'colors', 'intermediate', 'สีทอง', '金色', ARRAY['color', 'metallic', 'precious']),
('เงิน', '银色', 'ngəən', 'colors', 'intermediate', 'สีเงิน', '银色', ARRAY['color', 'metallic', 'precious']),
('ใส', '透明', 'sǎi', 'colors', 'intermediate', 'สีใส', '透明', ARRAY['color', 'transparent', 'clear']),

-- Body Parts (20 words)
('หัว', '头', 'hǔa', 'body', 'beginner', 'หัวของฉัน', '我的头', ARRAY['body', 'head', 'basic']),
('หน้า', '脸', 'nâa', 'body', 'beginner', 'หน้าสวย', '漂亮的脸', ARRAY['body', 'face', 'basic']),
('ตา', '眼睛', 'taa', 'body', 'beginner', 'ตาสวย', '漂亮的眼睛', ARRAY['body', 'face', 'sense']),
('หู', '耳朵', 'hǔu', 'body', 'beginner', 'หูของฉัน', '我的耳朵', ARRAY['body', 'head', 'sense']),
('จมูก', '鼻子', 'ja-mùuk', 'body', 'beginner', 'จมูกของฉัน', '我的鼻子', ARRAY['body', 'face', 'sense']),
('ปาก', '嘴巴', 'pàak', 'body', 'beginner', 'ปากของฉัน', '我的嘴巴', ARRAY['body', 'face', 'basic']),
('ฟัน', '牙齿', 'fan', 'body', 'beginner', 'ฟันขาว', '白牙齿', ARRAY['body', 'mouth', 'dental']),
('ลิ้น', '舌头', 'lín', 'body', 'beginner', 'ลิ้นของฉัน', '我的舌头', ARRAY['body', 'mouth', 'taste']),
('คอ', '脖子', 'khɔɔ', 'body', 'beginner', 'คอของฉัน', '我的脖子', ARRAY['body', 'neck', 'basic']),
('ไหล่', '肩膀', 'lài', 'body', 'beginner', 'ไหล่ของฉัน', '我的肩膀', ARRAY['body', 'shoulder', 'basic']),
('แขน', '手臂', 'khǎen', 'body', 'beginner', 'แขนของฉัน', '我的手臂', ARRAY['body', 'arm', 'basic']),
('มือ', '手', 'mɯɯ', 'body', 'beginner', 'มือของฉัน', '我的手', ARRAY['body', 'hand', 'basic']),
('นิ้ว', '手指', 'níw', 'body', 'beginner', 'นิ้วมือ', '手指', ARRAY['body', 'finger', 'basic']),
('หลัง', '背部', 'lǎng', 'body', 'beginner', 'หลังของฉัน', '我的背部', ARRAY['body', 'back', 'basic']),
('อก', '胸部', 'òk', 'body', 'beginner', 'อกของฉัน', '我的胸部', ARRAY['body', 'chest', 'basic']),
('ท้อง', '肚子', 'thɔ́ɔng', 'body', 'beginner', 'ท้องของฉัน', '我的肚子', ARRAY['body', 'stomach', 'basic']),
('ขา', '腿', 'khǎa', 'body', 'beginner', 'ขาของฉัน', '我的腿', ARRAY['body', 'leg', 'basic']),
('เข่า', '膝盖', 'khào', 'body', 'beginner', 'เข่าของฉัน', '我的膝盖', ARRAY['body', 'knee', 'joint']),
('เท้า', '脚', 'tháo', 'body', 'beginner', 'เท้าของฉัน', '我的脚', ARRAY['body', 'foot', 'basic']),
('ผม', '头发', 'phǒm', 'body', 'beginner', 'ผมยาว', '长头发', ARRAY['body', 'hair', 'appearance']),

-- Time and Days (20 words)
('เวลา', '时间', 'wee-laa', 'time', 'beginner', 'เวลาเท่าไหร่', '几点了', ARRAY['time', 'general', 'basic']),
('วัน', '天', 'wan', 'time', 'beginner', 'วันนี้', '今天', ARRAY['time', 'day', 'basic']),
('วันนี้', '今天', 'wan níi', 'time', 'beginner', 'วันนี้อากาศดี', '今天天气好', ARRAY['time', 'today', 'present']),
('เมื่อวาน', '昨天', 'mɯ̂a waan', 'time', 'beginner', 'เมื่อวานฝนตก', '昨天下雨', ARRAY['time', 'yesterday', 'past']),
('พรุ่งนี้', '明天', 'phrûng níi', 'time', 'beginner', 'พรุ่งนี้ไปทำงาน', '明天去工作', ARRAY['time', 'tomorrow', 'future']),
('วันจันทร์', '星期一', 'wan jan', 'time', 'beginner', 'วันจันทร์ทำงาน', '星期一工作', ARRAY['time', 'weekday', 'monday']),
('วันอังคาร', '星期二', 'wan ang-khaan', 'time', 'beginner', 'วันอังคารเรียน', '星期二上课', ARRAY['time', 'weekday', 'tuesday']),
('วันพุธ', '星期三', 'wan phút', 'time', 'beginner', 'วันพุธพักผ่อน', '星期三休息', ARRAY['time', 'weekday', 'wednesday']),
('วันพฤหัสบดี', '星期四', 'wan phá-rɯ́-hàt-sà-bɔɔ-dii', 'time', 'intermediate', 'วันพฤหัสบดีประชุม', '星期四开会', ARRAY['time', 'weekday', 'thursday']),
('วันศุกร์', '星期五', 'wan sùk', 'time', 'beginner', 'วันศุกร์เที่ยว', '星期五出游', ARRAY['time', 'weekday', 'friday']),
('วันเสาร์', '星期六', 'wan sǎo', 'time', 'beginner', 'วันเสาร์หยุด', '星期六休息', ARRAY['time', 'weekend', 'saturday']),
('วันอาทิตย์', '星期日', 'wan aa-thít', 'time', 'beginner', 'วันอาทิตย์พักผ่อน', '星期日休息', ARRAY['time', 'weekend', 'sunday']),
('เช้า', '早上', 'cháao', 'time', 'beginner', 'ตอนเช้า', '早上', ARRAY['time', 'morning', 'period']),
('เที่ยง', '中午', 'thîang', 'time', 'beginner', 'ตอนเที่ยง', '中午', ARRAY['time', 'noon', 'period']),
('บ่าย', '下午', 'bàai', 'time', 'beginner', 'ตอนบ่าย', '下午', ARRAY['time', 'afternoon', 'period']),
('เย็น', '傍晚', 'yen', 'time', 'beginner', 'ตอนเย็น', '傍晚', ARRAY['time', 'evening', 'period']),
('คืน', '夜晚', 'khɯɯn', 'time', 'beginner', 'ตอนคืน', '夜晚', ARRAY['time', 'night', 'period']),
('ชั่วโมง', '小时', 'chûa moong', 'time', 'intermediate', 'สองชั่วโมง', '两小时', ARRAY['time', 'duration', 'hour']),
('นาที', '分钟', 'naa-thii', 'time', 'intermediate', 'สิบนาที', '十分钟', ARRAY['time', 'duration', 'minute']),
('วินาที', '秒', 'wi-naa-thii', 'time', 'intermediate', 'สิบวินาที', '十秒', ARRAY['time', 'duration', 'second']),

-- Weather (15 words)
('อากาศ', '天气', 'aa-gàat', 'weather', 'beginner', 'อากาศดี', '天气好', ARRAY['weather', 'general', 'climate']),
('ฝน', '雨', 'fǒn', 'weather', 'beginner', 'ฝนตก', '下雨', ARRAY['weather', 'precipitation', 'wet']),
('แดด', '太阳', 'dàet', 'weather', 'beginner', 'แดดแรง', '太阳很强', ARRAY['weather', 'sun', 'hot']),
('ลม', '风', 'lom', 'weather', 'beginner', 'ลมแรง', '风很大', ARRAY['weather', 'wind', 'air']),
('เมฆ', '云', 'mêek', 'weather', 'beginner', 'เมฆมาก', '云很多', ARRAY['weather', 'cloud', 'sky']),
('ร้อน', '热', 'rɔ́ɔn', 'weather', 'beginner', 'อากาศร้อน', '天气热', ARRAY['weather', 'temperature', 'hot']),
('เย็น', '凉爽', 'yen', 'weather', 'beginner', 'อากาศเย็น', '天气凉爽', ARRAY['weather', 'temperature', 'cool']),
('หนาว', '冷', 'nǎao', 'weather', 'beginner', 'อากาศหนาว', '天气冷', ARRAY['weather', 'temperature', 'cold']),
('ชื้น', '潮湿', 'chɯ́ɯn', 'weather', 'intermediate', 'อากาศชื้น', '天气潮湿', ARRAY['weather', 'humidity', 'wet']),
('แห้ง', '干燥', 'hàeng', 'weather', 'intermediate', 'อากาศแห้ง', '天气干燥', ARRAY['weather', 'humidity', 'dry']),
('พายุ', '暴风雨', 'phaa-yu', 'weather', 'intermediate', 'พายุใหญ่', '大暴风雨', ARRAY['weather', 'storm', 'severe']),
('ฟ้าร้อง', '打雷', 'fáa rɔ́ɔng', 'weather', 'intermediate', 'ฟ้าร้องดัง', '雷声很大', ARRAY['weather', 'thunder', 'sound']),
('ฟ้าแลบ', '闪电', 'fáa lɛ́ɛp', 'weather', 'intermediate', 'ฟ้าแลบสว่าง', '闪电很亮', ARRAY['weather', 'lightning', 'bright']),
('หิมะ', '雪', 'hì-má', 'weather', 'intermediate', 'หิมะตก', '下雪', ARRAY['weather', 'snow', 'cold']),
('น้ำแข็ง', '冰', 'náam khǎeng', 'weather', 'beginner', 'น้ำแข็งแข็ง', '冰很硬', ARRAY['weather', 'ice', 'frozen']);

-- Update audio URLs for new vocabulary
UPDATE public.vocabulary
SET audio_url = '/audio/vocabulary/' || id || '.mp3'
WHERE category IN ('colors', 'body', 'time', 'weather');
